install.packages("tidyverse")
install.packages("rmarkdown")
install.packages("httr")
install.packages("shinydashboard")
install.packages('leaflet')
install.packages('leaflet')
install.packages('effsize')
install.packages('RcmdrMisc')
